#ifndef VERSION_H_INCLUDED
#define VERSION_H_INCLUDED

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define GIT_BRANCH "master"
#define GIT_HASH "f7c23ce"
#define BUILD_TIME "20210526100422"

#endif // VERSION_H_INCLUDED
